steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/preprocess:${SHORT_SHA}", "--target","preprocess"]
    id: Build-preprocess
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/preprocess"]
    id: Push-preprocess
