steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME/preprocess:${SHORT_SHA}", "--target","preprocess","."]
    id: Build-preprocess
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME/preprocess:${SHORT_SHA}"]
    id: Push-preprocess
