steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/github.com/preprocess:${SHORT_SHA}", "--target","preprocess","."]
    id: Build-preprocess
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/github.com/preprocess"]
    id: Push-preprocess
