steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/yashashwita/cloud_build_demo.git']
  id: 'clone repository'
- name: gcr.io/cloud-builders/gsutil
  args: ['-m', 'cp', '-r', 'requirements.txt', 'gs://us-central1-test2-61381588-bucket/']
  id: 'copy req file'
- name: gcr.io/cloud-builders/gsutil
  args: ['-m', 'cp', '-r', 'data/Iris_raw.csv', 'gs://us-central1-test-551aac04-bucket/dags/data']
  id: 'deploy-input-file'
- name: gcr.io/cloud-builders/gsutil
  args: ['-m', 'cp', '-r', 'dag_example.py', 'gs://us-central1-test-551aac04-bucket/dags/']
  dir: 'cloud_build_demo/'
  id: 'deploy-dag-file'