steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/preprocess:$COMMIT_SHA'
      - '--target'
      - 'preprocess'
      - .
      - '-f'
      - Dockerfile
    id: Build-preprocess
	
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/preprocess:$COMMIT_SHA'
    id: Push-preprocess
	
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/feature_engineering:$COMMIT_SHA'
      - '--target'
      - 'feature_engineering'
      - .
      - '-f'
      - Dockerfile
    id: Build-feature_engineering
	
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/feature_engineering:$COMMIT_SHA'
    id: Push-feature_engineering
	
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/model:$COMMIT_SHA'
      - '--target'
      - 'model'
      - .
      - '-f'
      - Dockerfile
    id: Build-model
	
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/model:$COMMIT_SHA'
    id: Push-model

images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/preprocess:$COMMIT_SHA'
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/feature_engineering:$COMMIT_SHA'
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/model:$COMMIT_SHA'
