steps:
- name: gcr.io/cloud-builders/gsutil
  args: ['-m', 'cp', '-r', 'data/Iris_raw.csv', 'gs://us-central1-test-551aac04-bucket/dags/data']
  id: 'deploy-input-file'
- name: gcr.io/cloud-builders/gsutil
  args: ['-m', 'cp', '-r', 'dag_example.py', 'gs://us-central1-test-551aac04-bucket/dags/']
  dir: 'cloud_build_demo/'
  id: 'deploy-dag-file'
- name: gcr.io/cloud-builders/gcloud
  args: ['composer', 'environments', 'run', 'test', '--location', 'us-central1', 'trigger_dag', '--', 'dag_example', '--run_id=$BUILD_ID']
  id: 'trigger-pipeline-execution'